### ISSUE TITLE
Seeders updated in Core 2.0.0.0, should no longer be an issue. Closing.

### ISSUE THREAD

**Issue by AGowans** [stratisproject/StratisCore#405]
This issue still exists on 2.0.

If you download 2.0 on a Win7 or Win10 machine, simply run the installer, and run the application, you will get the following message:

"Loading Failed - Unable to connect to a Stratis Node"

Seeders updated in Core 2.0.0.0, should no longer be an issue. Closing.

_Originally posted by @dev0tion in https://github.com/stratisproject/StratisCore/issues/344#issuecomment-574712760_

**Comment by dev0tion** [comment]
This is not what you said in #344, you said: "can't connect to a node".
Loading Failed - Unable to connect to a Stratis Node is a different animal. Most likely caused by a corrupt database or wallet file. Close Core, clear out %appdata%/StratisNode and start Core again, recover your wallet and you should be good to go.

If the problem persist, please check %appdata%/StratisNode/stratis/StratisMain/logs/node.txt. Scroll down to the bottom of the file and see if there's anything out of the ordinary. Could be an error/exception.

**Comment by dev0tion** [comment]
Closed due to inactivity. Ping me if still an issue.
