### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by clintnetwork** [stratisproject/StratisCore#84]
Hello,

I just build stratis core for linux (on archlinux) with the command `npm run package:linux`, i get a Stratis Core-v0.2.0-linux-x64.tar.gz file, that i have uncompressed, and when i launch ./stratis-core, i have this error:
![capture d ecran du 2018-10-10 15-25-27](https://user-images.githubusercontent.com/5221349/46739493-f6aa7500-cca0-11e8-9d93-1397088ed5cd.png)

Thank you

**Comment by clintm90** [comment]
@bokobza do you have an idea ?

**Comment by dev0tion** [comment]
@clintnetwork I think this means the daemon folder could not be found in the package.
Additionally to packaging the UI, you need to build the daemon and add the folder to the package.
Eventually you should have the Stratis.StratisD runable file here:
StratisCore.UI/daemon/Stratis.StratisD

Let me know if that fixed that for you.
You can always have a look at our buildscript build.sh to see what we do to build the complete package.

**Comment by clintnetwork** [comment]
Haa yes, thank you @dev0tion, i will try, but the wallet works well without this, i can open the wallet etc

**Comment by dev0tion** [comment]
It should work fine after clicking away the error message if you had a daemon running manually, correct.

**Comment by bokobza** [comment]
@dev0tion I think we should try to change the commands under [Build the UI for production](https://github.com/stratisproject/StratisCore#build-the-ui-for-production) to actually build the stuff for production or we should point to our scripts.
Let me try to do the former.

**Comment by D3m0nKingx** [comment]
@clintnetwork Firstly, re-clone the StratisCore github. as it has been renamed from FullNode.
when you build the StratisCore UI, there should be a **daemon** folder within StratisCore.UI  directory. 

This will package everything neatly into your resource folder path.

In this case the error you're getting is telling you that it's not finding the daemon executable in the path: StratisCore.UI/app-builds/StratisCore-v0.2.0-linux-x64/resources/daemon/**Stratis.StratisD**

You have to build the daemon first ( After cloning `git clone --recursive https://github.com/stratisproject/StratisCore` ), then:
```bash
~/clintm/Applications/StratisCore/StratisBitcoinFullNode/src/Stratis.StratisD$ dotnet publish -c Release -r ubuntu.16.04-x64 -o /home/clintm/Applications/StratisCore/StratisCore.UI/daemon
```

Then you can simply run from within StratisCore.UI: (If you have electron builder installed system-wide `sudo npm i -g electron-builder`):

- `build -l deb tar.gz `

Otherwise:

- `npm run package:linux`

**Comment by D3m0nKingx** [comment]
@clintnetwork answering your other question:

### What is asar: (electron-builder option)

- asar = true AsarOptions | Boolean - Whether to package the application’s source code into an archive, using Electron’s archive format.

- Node modules, that must be unpacked, will be detected automatically, you don’t need to explicitly set asarUnpack - please file an issue if this doesn’t work.
 
- smartUnpack = true Boolean - Whether to automatically unpack executables files.
ordering String
- asarUnpack Array<String> | String - A glob patterns relative to the app directory, which specifies which files to unpack when creating the asar archive.

**Comment by D3m0nKingx** [comment]
![image](https://user-images.githubusercontent.com/18432686/47199564-2a8c3700-d340-11e8-96f5-e0d4651f497b.png)

:100:

**Comment by clintnetwork** [comment]
Hello,

Very thank you for your answers, i've understand this yesterday when i've seen StratisFullNode folder but i did not know this command `git clone --recursive` 
I will re-git clone and rebuild  with your informations

Thanks

**Comment by dev0tion** [comment]
Great! Closing.
